# Generated by Django 2.2.24 on 2024-11-08 18:58

from django.db import migrations

def add_new_building(apps, schema_editor):
    buildings = apps.get_model('property', 'Flat')
    [
        (
            building.objects.get_or_create(
                new_building = True
                ),
            building.save()
            )
        if building.construction_year >= 2015
        else (
            building.objects.get_or_create(
                new_building = False
                ),
            building.save()
            )
        for building in buildings.objects.all()
        ]


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(add_new_building),
    ]
