# Generated by Django 2.2.24 on 2024-12-05 19:12

from django.db import migrations


def add_owners(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    Owner = apps.get_model('property','Owner')

    for flat in Flat.objects.all().iterator():
        Owner.objects.get_or_create(name=flat.owner, defaults = {
            'phone': flat.owners_phonenumber,
            'owner_pure_phone': flat.owner_pure_phone,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20241202_2321'),
    ]

    operations = [
        migrations.RunPython(add_owners),
    ]
