# Generated by Django 2.2.24 on 2024-12-11 18:46

from django.db import migrations

def owner_to_flat(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    Owner = apps.get_model('property','Owner')

    for owner in Owner.objects.iterator():
        owner_flats = Flat.objects.filter(owner=owner.name)
        owner.flats.set(owner_flats)
        owner.save()

def move_backwards(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.iterator():
        owner.flats = []
        owner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(owner_to_flat,
                             move_backwards),
    ]
