# Generated by Django 2.2.24 on 2025-01-10 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_on_flat', to='property.Flat', verbose_name='Квартира, на которую жалуются'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_сomplaints', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который жалуется'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_on_flat', to=settings.AUTH_USER_MODEL, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(null=True, related_name='owner_flat', to='property.Flat', verbose_name='Квартира, кототорая продается'),
        ),
    ]
